### ISSUE TITLE
SoundCloud | soundcloud.com

### ISSUE THREAD

**Issue by flornian** [PreMiD/Presences#5056]
### Description

SoundCloud RPC doesn't show up (it used to work). Other services such as YouTube work fine.

Error in terminal after running premid:
```
Opened socket
Socket connection
Create RPC client (463097721130188830)
Clear all activity
Create RPC client (802958833214423081)
Destroy RPC client (802958833214423081)
Error: connection closed
    at /opt/PreMiD/resources/app.asar/node_modules/discord-rpc/src/client.js:115:20
    at Map.forEach (<anonymous>)
    at IPCTransport.<anonymous> (/opt/PreMiD/resources/app.asar/node_modules/discord-rpc/src/client.js:114:25)
    at Object.onceWrapper (events.js:417:26)
    at IPCTransport.emit (events.js:322:22)
    at /opt/PreMiD/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:141:18
    at decode (/opt/PreMiD/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:92:5)
    at Socket.<anonymous> (/opt/PreMiD/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:120:7)
    at Socket.emit (events.js:310:20)
    at emitReadable_ (_stream_readable.js:543:12)
```

### Steps to Reproduce

1. Run PreMiD
2. Listen to SoundCloud
3. Check terminal for error

### Expected Behavior

I expected it to just put "Playing SoundCloud" on my Discord profile

### Operating System (OS)

Ubuntu 21.04

### Browser

Firefox

### Browser Version

95.0

**Comment by flornian** [comment]
Tried again today, works fine now. Don't know why it didn't work
